


/*
 * Tabuleiro.java
 *
 * Created on 22/03/2010, 19:58:42
 */
package br.com.assinchronus.gui;
/**
 *
 * @author Matheus
 */
public class Jogo extends javax.swing.JFrame {

    /** Creates new form Tabuleiro */
    public Jogo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 850));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setEnabled(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 650, 89, 89);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 650, 89, 89);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setEnabled(false);
        getContentPane().add(jButton3);
        jButton3.setBounds(190, 650, 89, 89);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton4);
        jButton4.setBounds(280, 650, 89, 89);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setEnabled(false);
        getContentPane().add(jButton5);
        jButton5.setBounds(370, 650, 89, 89);

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton6);
        jButton6.setBounds(460, 650, 89, 89);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setEnabled(false);
        getContentPane().add(jButton7);
        jButton7.setBounds(550, 650, 89, 89);

        jButton8.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton8);
        jButton8.setBounds(640, 650, 89, 89);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setEnabled(false);
        getContentPane().add(jButton9);
        jButton9.setBounds(640, 560, 89, 89);

        jButton10.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton10);
        jButton10.setBounds(10, 560, 89, 89);

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setEnabled(false);
        getContentPane().add(jButton11);
        jButton11.setBounds(100, 560, 89, 89);

        jButton12.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton12);
        jButton12.setBounds(190, 560, 89, 89);

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setEnabled(false);
        getContentPane().add(jButton13);
        jButton13.setBounds(280, 560, 89, 89);

        jButton14.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton14);
        jButton14.setBounds(370, 560, 89, 89);

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setEnabled(false);
        getContentPane().add(jButton15);
        jButton15.setBounds(460, 560, 89, 89);

        jButton16.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton16);
        jButton16.setBounds(550, 560, 89, 89);

        jButton17.setBackground(new java.awt.Color(255, 255, 255));
        jButton17.setEnabled(false);
        getContentPane().add(jButton17);
        jButton17.setBounds(10, 470, 89, 89);

        jButton18.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton18);
        jButton18.setBounds(100, 470, 89, 89);

        jButton19.setBackground(new java.awt.Color(255, 255, 255));
        jButton19.setEnabled(false);
        getContentPane().add(jButton19);
        jButton19.setBounds(190, 470, 89, 89);

        jButton20.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton20);
        jButton20.setBounds(280, 470, 89, 89);

        jButton21.setBackground(new java.awt.Color(255, 255, 255));
        jButton21.setEnabled(false);
        getContentPane().add(jButton21);
        jButton21.setBounds(370, 470, 89, 89);

        jButton22.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton22);
        jButton22.setBounds(460, 470, 89, 89);

        jButton23.setBackground(new java.awt.Color(255, 255, 255));
        jButton23.setEnabled(false);
        getContentPane().add(jButton23);
        jButton23.setBounds(550, 470, 89, 89);

        jButton24.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton24);
        jButton24.setBounds(640, 470, 89, 89);

        jButton25.setBackground(new java.awt.Color(255, 255, 255));
        jButton25.setEnabled(false);
        getContentPane().add(jButton25);
        jButton25.setBounds(640, 380, 89, 89);

        jButton26.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton26);
        jButton26.setBounds(10, 380, 89, 89);

        jButton27.setBackground(new java.awt.Color(255, 255, 255));
        jButton27.setEnabled(false);
        getContentPane().add(jButton27);
        jButton27.setBounds(100, 380, 89, 89);

        jButton28.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton28);
        jButton28.setBounds(190, 380, 89, 89);

        jButton29.setBackground(new java.awt.Color(255, 255, 255));
        jButton29.setEnabled(false);
        getContentPane().add(jButton29);
        jButton29.setBounds(280, 380, 89, 89);

        jButton30.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton30);
        jButton30.setBounds(370, 380, 89, 89);

        jButton31.setBackground(new java.awt.Color(255, 255, 255));
        jButton31.setEnabled(false);
        getContentPane().add(jButton31);
        jButton31.setBounds(460, 380, 89, 89);

        jButton32.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton32);
        jButton32.setBounds(550, 380, 89, 89);

        jButton33.setBackground(new java.awt.Color(255, 255, 255));
        jButton33.setEnabled(false);
        getContentPane().add(jButton33);
        jButton33.setBounds(10, 290, 89, 89);

        jButton34.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton34);
        jButton34.setBounds(100, 290, 89, 89);

        jButton35.setBackground(new java.awt.Color(255, 255, 255));
        jButton35.setEnabled(false);
        getContentPane().add(jButton35);
        jButton35.setBounds(190, 290, 89, 89);

        jButton36.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton36);
        jButton36.setBounds(280, 290, 89, 89);

        jButton37.setBackground(new java.awt.Color(255, 255, 255));
        jButton37.setEnabled(false);
        getContentPane().add(jButton37);
        jButton37.setBounds(370, 290, 89, 89);

        jButton38.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton38);
        jButton38.setBounds(460, 290, 89, 89);

        jButton39.setBackground(new java.awt.Color(255, 255, 255));
        jButton39.setEnabled(false);
        getContentPane().add(jButton39);
        jButton39.setBounds(550, 290, 89, 89);

        jButton40.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton40);
        jButton40.setBounds(640, 290, 89, 89);

        jButton41.setBackground(new java.awt.Color(255, 255, 255));
        jButton41.setEnabled(false);
        getContentPane().add(jButton41);
        jButton41.setBounds(640, 200, 89, 89);

        jButton42.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton42);
        jButton42.setBounds(10, 200, 89, 89);

        jButton43.setBackground(new java.awt.Color(255, 255, 255));
        jButton43.setEnabled(false);
        getContentPane().add(jButton43);
        jButton43.setBounds(100, 200, 89, 89);

        jButton44.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton44);
        jButton44.setBounds(190, 200, 89, 89);

        jButton45.setBackground(new java.awt.Color(255, 255, 255));
        jButton45.setEnabled(false);
        getContentPane().add(jButton45);
        jButton45.setBounds(280, 200, 89, 89);

        jButton46.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton46);
        jButton46.setBounds(370, 200, 89, 89);

        jButton47.setBackground(new java.awt.Color(255, 255, 255));
        jButton47.setEnabled(false);
        getContentPane().add(jButton47);
        jButton47.setBounds(460, 200, 89, 89);

        jButton48.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton48);
        jButton48.setBounds(550, 200, 89, 89);

        jButton49.setBackground(new java.awt.Color(255, 255, 255));
        jButton49.setEnabled(false);
        getContentPane().add(jButton49);
        jButton49.setBounds(10, 110, 89, 89);

        jButton50.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton50);
        jButton50.setBounds(100, 110, 89, 89);

        jButton51.setBackground(new java.awt.Color(255, 255, 255));
        jButton51.setEnabled(false);
        getContentPane().add(jButton51);
        jButton51.setBounds(190, 110, 89, 89);

        jButton52.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton52);
        jButton52.setBounds(280, 110, 89, 89);

        jButton53.setBackground(new java.awt.Color(255, 255, 255));
        jButton53.setEnabled(false);
        getContentPane().add(jButton53);
        jButton53.setBounds(370, 110, 89, 89);

        jButton54.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton54);
        jButton54.setBounds(460, 110, 89, 89);

        jButton55.setBackground(new java.awt.Color(255, 255, 255));
        jButton55.setEnabled(false);
        getContentPane().add(jButton55);
        jButton55.setBounds(550, 110, 89, 89);

        jButton56.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jButton56);
        jButton56.setBounds(640, 110, 89, 89);

        jButton57.setBackground(new java.awt.Color(255, 255, 255));
        jButton57.setEnabled(false);
        getContentPane().add(jButton57);
        jButton57.setBounds(640, 20, 89, 89);
 
        jButton58.setBackground(new java.awt.Color(102, 102, 102));
        jButton58.setIcon(new javax.swing.ImageIcon( "src/images/peca.png")); // NOI18N
        getContentPane().add(jButton58);
        jButton58.setBounds(10, 20, 89, 89);

        jButton59.setBackground(new java.awt.Color(255, 255, 255));
        jButton59.setEnabled(false);
        getContentPane().add(jButton59);
        jButton59.setBounds(100, 20, 89, 89);

        jButton60.setBackground(new java.awt.Color(102, 102, 102));
        jButton60.setIcon(new javax.swing.ImageIcon("src/images/pecapreta.png")); // NOI18N
        getContentPane().add(jButton60);
        jButton60.setBounds(190, 20, 89, 89);

        jButton61.setBackground(new java.awt.Color(255, 255, 255));
        jButton61.setEnabled(false);
        getContentPane().add(jButton61);
        jButton61.setBounds(280, 20, 89, 89);

        jButton62.setBackground(new java.awt.Color(102, 102, 102));
        jButton62.setIcon(new javax.swing.ImageIcon("src/images/dama.png")); // NOI18N
        getContentPane().add(jButton62);
        jButton62.setBounds(370, 20, 89, 89);

        jButton63.setBackground(new java.awt.Color(255, 255, 255));
        jButton63.setEnabled(false);
        getContentPane().add(jButton63);
        jButton63.setBounds(460, 20, 89, 89);

        jButton64.setBackground(new java.awt.Color(102, 102, 102));
        jButton64.setIcon(new javax.swing.ImageIcon("src/images/damapreta.png")); // NOI18N
        getContentPane().add(jButton64);
        jButton64.setBounds(550, 20, 89, 89);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
